export const hotelTypes = [
  "Budget",
  "Boutique",
  "Luxury",
  "Ski Resort",
  "Business",
  "Family",
  "Romantic",
  "Hiking Resort",
  "Cabin",
  "Lease",
  "SubLease",
  "Motel",
  "All Inclusive",
  "Pet Friendly",
  "Self Catering",
]

export const hotelFacilities = [
    "Restaurant",
    "Nearby Transportation",
    "Free WiFi",
    "Parking",
    "Airport Shuttle",
    "Family Rooms",
    "Non-Smoking Rooms",
    "Outdoor Pool",
    "Spa",
    "Fitness Center",
]
